[capabilities.ssh]
volumes = ["~/.ssh:~/.ssh:ro"]

[capabilities.git]
volumes = ["~/.gitconfig:~/.gitconfig:ro"]

[capabilities.wayland]
env = ["WAYLAND_DISPLAY", "XDG_RUNTIME_DIR"]
volumes = ["$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY"]

[capabilities.rust]
path = ["~/.cargo/bin"]

[capabilities.claude]
volumes = [
    "~/.claude:~/.claude",
    "~/.claude.json:~/.claude.json",
]

[capabilities.default]
volumes = ["~/.config/isolation:~:rw"]
